# PyInstaller build spec for AstraNova.  Build with:  build.bat   (or: build.bat public)
import os
import sys

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

ROOT = os.path.abspath(SPECPATH)  # noqa: F821  (provided by PyInstaller)
PKG = "astra"
sys.path.insert(0, ROOT)

pkg_dir = os.path.join(ROOT, PKG)
if not os.path.isfile(os.path.join(pkg_dir, "__init__.py")):
    raise SystemExit(f"Build error: {pkg_dir}\\__init__.py is missing. Re-extract the zip into an empty folder.")

# Every app module, listed explicitly so nothing can be left out of the exe.
modules, sources = [], []
for base, dirs, files in os.walk(pkg_dir):
    dirs[:] = [d for d in dirs if d != "__pycache__"]
    for f in files:
        if f.endswith(".py"):
            full = os.path.join(base, f)
            rel = os.path.relpath(full, ROOT)[:-3].replace(os.sep, ".")
            modules.append(rel[: -len(".__init__")] if rel.endswith(".__init__") else rel)
            sources.append((full, os.path.relpath(base, ROOT)))  # source fallback next to the exe
print(f"AstraNova: bundling {len(modules)} modules from {pkg_dir}")

# public edition
EDITION = "public"
APP = "AstraNova"
os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
edition_file = os.path.join(ROOT, "build", "edition.txt")
with open(edition_file, "w", encoding="utf-8") as f:
    f.write(EDITION)
print(f"AstraNova: building the {EDITION} edition")

# Every library the app imports (read straight from the source, including lazy imports inside functions).
import ast  # noqa: E402

lib_imports = set()
for full, _ in sources:
    tree = ast.parse(open(full, encoding="utf-8").read(), full)
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            lib_imports.update(n.name for n in node.names)
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            lib_imports.add(node.module)
lib_imports = sorted(m for m in lib_imports if not m.startswith(PKG))
print(f"AstraNova: {len(lib_imports)} libraries used by the app")

DEEP = ("email", "playwright", "bs4", "requests", "keyring", "webview", "urllib", "http", "concurrent", "discord",
        "spotipy", "mss", "pywinauto", "comtypes", "pyperclip", "psutil", "aiohttp")
lib_hidden = []
for m in lib_imports:
    lib_hidden.append(m)
    top = m.split(".")[0]
    if top in DEEP:
        lib_hidden += collect_submodules(top)

datas = [(os.path.join(ROOT, "ui"), "ui"), (os.path.join(ROOT, "assets"), "assets"), (edition_file, ".")] + sources
datas += collect_data_files("playwright")
datas += collect_data_files("webview")
datas += collect_data_files("certifi")
try:   # the microphone library ships PortAudio as a data package
    datas += collect_data_files("_sounddevice_data")
except Exception:
    pass

BUILD_ONLY = ("PyInstaller", "_pyinstaller_hooks_contrib", "pyinstaller", "altgraph", "pefile", "macholib")


def runtime_module(name):
    return "__pyinstaller" not in name and not name.split(".")[0] in BUILD_ONLY


def wanted(name):
    return runtime_module(name) and ".tests" not in name and ".test_" not in name


extra = ["keyring.backends.Windows", "clr", "sounddevice", "_sounddevice_data", "_cffi_backend", "PIL.Image", "PIL.ImageDraw", "PIL.ImageFont", "PIL.ImageEnhance",
         "PIL.ImageFilter", "PIL.ImageOps", "PIL.ImageColor", "PIL.PngImagePlugin", "PIL.JpegImagePlugin",
         "PIL.WebPImagePlugin", "PIL.BmpImagePlugin", "PIL.GifImagePlugin", "PIL.TiffImagePlugin"]
if sys.platform == "win32":
    extra += ["win32api", "win32con", "win32gui", "win32process", "pythoncom", "pywintypes"]
    try:
        extra += collect_submodules("comtypes.gen")  # UI Automation bindings generated by build.bat
    except Exception:
        pass

hiddenimports = sorted(m for m in set(modules + lib_hidden + collect_submodules("webview", filter=runtime_module) + extra)
                       if wanted(m))

a = Analysis(
    [os.path.join(ROOT, "main.py")],
    pathex=[ROOT],
    datas=datas,
    hiddenimports=hiddenimports,
    excludes=["tkinter", "matplotlib", "numpy", "pandas", "scipy", "webview.__pyinstaller", *BUILD_ONLY],
)
leaked = sorted({name.split(".")[0] for name, *_ in a.pure if not runtime_module(name)})
if leaked:
    raise SystemExit(f"Build error: build-only packages would be bundled: {leaked}")
missing = [m for m in modules if m not in {name for name, *_ in a.pure}]
print("AstraNova: modules in bundle:", len(modules) - len(missing), "/", len(modules),
      ("(missing from bytecode, using source fallback: " + ", ".join(missing) + ")") if missing else "")

pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name=APP,
    icon=os.path.join(ROOT, "assets", "astra.ico"),
    console=False,
    upx=False,
)
coll = COLLECT(exe, a.binaries, a.datas, name=APP, upx=False)
